#!/usr/bin/env bash
#
# ChainLogistics — full testnet deploy + wire.
#
# Deploys the MVP "core trio" from a single WASM:
#   * MAIN  — ProductRegistry + ChainLogistics + Validation (shared storage).
#             This is the address the frontend/backend point NEXT_PUBLIC_CONTRACT_ID at.
#   * AUTH  — AuthorizationContract (product ownership / authorized actors).
#
# Both instances are instantiated from ONE uploaded WASM hash, then wired:
#   1. AUTH.configure_initializer(MAIN)   — only MAIN may seed product owners
#   2. MAIN.init(admin, AUTH)             — sets admin, unpauses, stores auth addr
#   3. MAIN.configure_auth_contract(AUTH) — idempotent belt-and-braces
#
# Requirements: stellar-cli >= 27 (soroban-sdk 25.3.1 targets protocol 27),
#               rustup target wasm32v1-none.
#
# Usage:
#   ./scripts/deploy-testnet.sh                 # uses/creates identity "chainlog-deployer"
#   ./scripts/deploy-testnet.sh --network testnet --identity my-key
#
set -euo pipefail

RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'; NC='\033[0m'
info()  { echo -e "${GREEN}$*${NC}"; }
warn()  { echo -e "${YELLOW}$*${NC}"; }
die()   { echo -e "${RED}Error: $*${NC}" >&2; exit 1; }

NETWORK="testnet"
IDENTITY="chainlog-deployer"
RPC_URL="https://soroban-testnet.stellar.org"
PASSPHRASE="Test SDF Network ; September 2015"
CONTRACT_NAME="chainlogistics"
TARGET="wasm32v1-none"

while [[ $# -gt 0 ]]; do
  case "$1" in
    --network)  NETWORK="$2"; shift 2;;
    --identity) IDENTITY="$2"; shift 2;;
    --rpc-url)  RPC_URL="$2";  shift 2;;
    --help)
      grep '^#' "$0" | sed 's/^# \{0,1\}//'; exit 0;;
    *) die "Unknown option: $1 (see --help)";;
  esac
done

command -v stellar >/dev/null || die "stellar CLI not found. Install stellar-cli >= 27."
CLI_MAJOR=$(stellar version 2>/dev/null | grep -oE 'stellar [0-9]+' | head -1 | grep -oE '[0-9]+' || echo 0)
[[ "$CLI_MAJOR" -ge 27 ]] || warn "stellar-cli major is $CLI_MAJOR; >= 27 recommended for soroban-sdk 25.x."

cd "$(dirname "$0")/.."   # -> smart-contract/
SC_DIR="$(pwd)"
WASM="target/${TARGET}/release/${CONTRACT_NAME}.wasm"

# ── Network config (idempotent) ──────────────────────────────────────────────
stellar network add "$NETWORK" --rpc-url "$RPC_URL" --network-passphrase "$PASSPHRASE" 2>/dev/null || true

# ── Identity (create + fund on testnet if missing) ───────────────────────────
if ! stellar keys address "$IDENTITY" >/dev/null 2>&1; then
  info "Creating identity '$IDENTITY'..."
  if [[ "$NETWORK" == "testnet" || "$NETWORK" == "futurenet" ]]; then
    stellar keys generate "$IDENTITY" --network "$NETWORK" --fund
  else
    stellar keys generate "$IDENTITY"
    warn "Fund $IDENTITY manually before deploying to $NETWORK."
  fi
fi
ADMIN=$(stellar keys address "$IDENTITY")
info "Deployer / admin: $ADMIN"

# ── Build ────────────────────────────────────────────────────────────────────
info "Building WASM ($TARGET)..."
rustup target add "$TARGET" >/dev/null 2>&1 || true
cargo build --target "$TARGET" --release
[[ -f "$WASM" ]] || die "WASM not found at $WASM"

SRC=(--source "$IDENTITY" --network "$NETWORK")

# ── Upload once, instantiate twice ───────────────────────────────────────────
info "Uploading WASM..."
HASH=$(stellar contract upload --wasm "$WASM" "${SRC[@]}")
info "  wasm hash: $HASH"

info "Instantiating MAIN..."
MAIN=$(stellar contract deploy --wasm-hash "$HASH" "${SRC[@]}")
info "  MAIN: $MAIN"

info "Instantiating AUTH..."
AUTH=$(stellar contract deploy --wasm-hash "$HASH" "${SRC[@]}")
info "  AUTH: $AUTH"

# ── Wire ─────────────────────────────────────────────────────────────────────
info "Wiring AUTH.configure_initializer(MAIN)..."
stellar contract invoke --id "$AUTH" "${SRC[@]}" --send=yes -- \
  configure_initializer --initializer "$MAIN" >/dev/null

info "Wiring MAIN.init(admin, AUTH)..."
stellar contract invoke --id "$MAIN" "${SRC[@]}" --send=yes -- \
  init --admin "$ADMIN" --auth_contract "$AUTH" >/dev/null

info "Wiring MAIN.configure_auth_contract(AUTH)..."
stellar contract invoke --id "$MAIN" "${SRC[@]}" --send=yes -- \
  configure_auth_contract --auth_contract "$AUTH" >/dev/null || true

# ── Persist addresses ────────────────────────────────────────────────────────
ENV_FILE="${SC_DIR}/.env"
{
  echo "# Generated by deploy-testnet.sh"
  echo "NETWORK=${NETWORK}"
  echo "RPC_URL=${RPC_URL}"
  echo "ADMIN_ADDRESS=${ADMIN}"
  echo "CONTRACT_ID=${MAIN}"
  echo "MAIN_CONTRACT_ID=${MAIN}"
  echo "AUTH_CONTRACT_ID=${AUTH}"
  echo "WASM_HASH=${HASH}"
} > "$ENV_FILE"
info "Wrote $ENV_FILE"

# Frontend env (MAIN is the single address the frontend needs)
FE_ENV="${SC_DIR}/../frontend/.env.local"
touch "$FE_ENV"
for k in NEXT_PUBLIC_CONTRACT_ID NEXT_PUBLIC_STELLAR_NETWORK NEXT_PUBLIC_RPC_URL NEXT_PUBLIC_STELLAR_CONTRACT_ID; do
  sed -i "/^${k}=/d" "$FE_ENV" 2>/dev/null || true
done
{
  echo "NEXT_PUBLIC_CONTRACT_ID=${MAIN}"
  echo "NEXT_PUBLIC_STELLAR_NETWORK=${NETWORK}"
  echo "NEXT_PUBLIC_RPC_URL=${RPC_URL}"
  echo "NEXT_PUBLIC_STELLAR_CONTRACT_ID=${MAIN}"
} >> "$FE_ENV"
info "Updated $FE_ENV"

echo ""
info "════════════════════════════════════════════════════════════════"
info " Deployment complete on ${NETWORK}"
info "   MAIN (NEXT_PUBLIC_CONTRACT_ID): ${MAIN}"
info "   AUTH:                           ${AUTH}"
info "   Admin:                          ${ADMIN}"
info "   WASM hash:                      ${HASH}"
info "════════════════════════════════════════════════════════════════"
